name: Docs Build

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install sphinx sphinx_rtd_theme

      - name: Build documentation
        run: |
          cd docs
          make html
